PUBLISH_TYPE_ENUM_CHARACTER = 'CHARACTER'
"""Export Type: Character"""

PUBLISH_TYPE_ENUM_ACTOR = 'ACTOR'
"""Export Type: Actor"""


PUBLISH_TYPE_ENUM_ITEMS = [
    (PUBLISH_TYPE_ENUM_CHARACTER, PUBLISH_TYPE_ENUM_CHARACTER.title(), ''),
    (PUBLISH_TYPE_ENUM_ACTOR, PUBLISH_TYPE_ENUM_ACTOR.title(), '')
]

ASSET_TYPE_ENUM_ITEMS = [
    ('CHARACTER', 'Character', ''),
    ('ACTOR', 'Actor', 'Rigged props'),
]